# Generated by Django 5.1.7 on 2025-03-24 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Title')),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In progress'), ('shipped', 'Shipped')], default='received', max_length=20)),
                ('repair_start_date', models.DateTimeField()),
                ('repair_end_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery', models.ImageField(blank=True, upload_to='proofs')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repair shipment',
                'verbose_name_plural': 'Repair shipments',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Title')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx'), ('dhl', 'DHL'), ('ferrari', 'FERARRI'), ('other', 'OTHER')], max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('received', 'Received')], max_length=20)),
                ('commercial_invoice', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('shipping_to', models.CharField(choices=[('harrods', 'Harrods'), ('liberty', 'Liberty'), ('dublin', 'Dublin'), ('dubai_mall', 'Dubai Mall'), ('moe', 'MOE')], max_length=100)),
                ('shipping_from', models.CharField(choices=[('harrods', 'Harrods'), ('liberty', 'Liberty'), ('dublin', 'Dublin'), ('dubai_mall', 'Dubai Mall'), ('moe', 'MOE')], max_length=100)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
