# Generated by Django 5.1.7 on 2025-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=123, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=123, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/user_avatar', verbose_name='Avatar')),
                ('role', models.PositiveIntegerField(choices=[(1, 'Normal User'), (2, 'Moderator'), (3, 'Accountant')], default=1, verbose_name='Role')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
